// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickTypeCList;
//
//    var countryList = CountryList.FromJson(jsonString);

namespace QuickTypeCList
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CountryList
    {
        [JsonProperty("Code")]
        public string Code { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }
    }

    public partial class CountryList
    {
        public static List<CountryList> FromJson(string json) => JsonConvert.DeserializeObject<List<CountryList>>(json, QuickTypeCList.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<CountryList> self) => JsonConvert.SerializeObject(self, QuickTypeCList.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
